/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

/**
 *
 * @author User
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v0 = new javax.swing.JButton();
        v2 = new javax.swing.JButton();
        v1 = new javax.swing.JButton();
        v3 = new javax.swing.JButton();
        v4 = new javax.swing.JButton();
        v9 = new javax.swing.JButton();
        v5 = new javax.swing.JButton();
        v6 = new javax.swing.JButton();
        v7 = new javax.swing.JButton();
        v8 = new javax.swing.JButton();
        v10 = new javax.swing.JButton();
        v11 = new javax.swing.JButton();
        v12 = new javax.swing.JButton();
        v13 = new javax.swing.JButton();
        v14 = new javax.swing.JButton();
        v15 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        v0.setBackground(new java.awt.Color(0, 0, 0));
        v0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v0.setForeground(new java.awt.Color(255, 255, 255));
        v0.setText("0");
        v0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v0ActionPerformed(evt);
            }
        });

        v2.setBackground(new java.awt.Color(0, 0, 0));
        v2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v2.setForeground(new java.awt.Color(255, 255, 255));
        v2.setText("2");
        v2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ActionPerformed(evt);
            }
        });

        v1.setBackground(new java.awt.Color(0, 0, 0));
        v1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v1.setForeground(new java.awt.Color(255, 255, 255));
        v1.setText("1");
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });

        v3.setBackground(new java.awt.Color(0, 0, 0));
        v3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v3.setForeground(new java.awt.Color(255, 255, 255));
        v3.setText("3");
        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });

        v4.setBackground(new java.awt.Color(0, 0, 0));
        v4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v4.setForeground(new java.awt.Color(255, 255, 255));
        v4.setText("4");
        v4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v4ActionPerformed(evt);
            }
        });

        v9.setBackground(new java.awt.Color(0, 0, 0));
        v9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v9.setForeground(new java.awt.Color(255, 255, 255));
        v9.setText("9");
        v9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v9ActionPerformed(evt);
            }
        });

        v5.setBackground(new java.awt.Color(0, 0, 0));
        v5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v5.setForeground(new java.awt.Color(255, 255, 255));
        v5.setText("5");
        v5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v5ActionPerformed(evt);
            }
        });

        v6.setBackground(new java.awt.Color(0, 0, 0));
        v6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v6.setForeground(new java.awt.Color(255, 255, 255));
        v6.setText("6");
        v6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v6ActionPerformed(evt);
            }
        });

        v7.setBackground(new java.awt.Color(0, 0, 0));
        v7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v7.setForeground(new java.awt.Color(255, 255, 255));
        v7.setText("7");
        v7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v7ActionPerformed(evt);
            }
        });

        v8.setBackground(new java.awt.Color(0, 0, 0));
        v8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v8.setForeground(new java.awt.Color(255, 255, 255));
        v8.setText("8");
        v8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v8ActionPerformed(evt);
            }
        });

        v10.setBackground(new java.awt.Color(0, 0, 0));
        v10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v10.setForeground(new java.awt.Color(255, 255, 255));
        v10.setText("+");
        v10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v10ActionPerformed(evt);
            }
        });

        v11.setBackground(new java.awt.Color(0, 0, 0));
        v11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v11.setForeground(new java.awt.Color(255, 255, 255));
        v11.setText("-");
        v11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v11ActionPerformed(evt);
            }
        });

        v12.setBackground(new java.awt.Color(0, 0, 0));
        v12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v12.setForeground(new java.awt.Color(255, 255, 255));
        v12.setText("*");
        v12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v12ActionPerformed(evt);
            }
        });

        v13.setBackground(new java.awt.Color(0, 0, 0));
        v13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v13.setForeground(new java.awt.Color(255, 255, 255));
        v13.setText("/");
        v13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v13ActionPerformed(evt);
            }
        });

        v14.setBackground(new java.awt.Color(0, 0, 0));
        v14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v14.setForeground(new java.awt.Color(255, 255, 255));
        v14.setText("%");
        v14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v14ActionPerformed(evt);
            }
        });

        v15.setBackground(new java.awt.Color(0, 0, 0));
        v15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        v15.setForeground(new java.awt.Color(255, 255, 255));
        v15.setText("=");
        v15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v15ActionPerformed(evt);
            }
        });

        display.setBackground(new java.awt.Color(204, 204, 204));
        display.setColumns(20);
        display.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(v0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(v10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(v15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v0)
                    .addComponent(v1)
                    .addComponent(v2)
                    .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v5)
                    .addComponent(v6)
                    .addComponent(v7)
                    .addComponent(v8)
                    .addComponent(v9))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v10)
                    .addComponent(v11)
                    .addComponent(v12)
                    .addComponent(v13)
                    .addComponent(v14))
                .addGap(35, 35, 35)
                .addComponent(v15)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void v0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v0ActionPerformed
        display.setText(display.getText()+"0");
    }//GEN-LAST:event_v0ActionPerformed

    private void v2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2ActionPerformed
        display.setText(display.getText()+"2");
    }//GEN-LAST:event_v2ActionPerformed

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        display.setText(display.getText()+"1");
    }//GEN-LAST:event_v1ActionPerformed

    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v3ActionPerformed

    private void v4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v4ActionPerformed

    private void v9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v9ActionPerformed

    private void v5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v5ActionPerformed

    private void v6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v6ActionPerformed

    private void v7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v7ActionPerformed

    private void v8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v8ActionPerformed

    private void v10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v10ActionPerformed
        display.setText(display.getText()+"+");
    }//GEN-LAST:event_v10ActionPerformed

    private void v11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v11ActionPerformed
        display.setText(display.getText()+"-");
    }//GEN-LAST:event_v11ActionPerformed

    private void v12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v12ActionPerformed

    private void v13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v13ActionPerformed

    private void v14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v14ActionPerformed

    private void v15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v15ActionPerformed
 

        String text=display.getText();
        double a=Double.parseDouble(text.substring(0, 1));
        double b=Double.parseDouble(text.substring(2));
        String op=text.substring(1,2);
        double result=0;
        display.setText("");
        if(op.equals("+")){
        result =a+b;
        }
        display.setText(String.valueOf(result));
    }//GEN-LAST:event_v15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea display;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton v0;
    private javax.swing.JButton v1;
    private javax.swing.JButton v10;
    private javax.swing.JButton v11;
    private javax.swing.JButton v12;
    private javax.swing.JButton v13;
    private javax.swing.JButton v14;
    private javax.swing.JButton v15;
    private javax.swing.JButton v2;
    private javax.swing.JButton v3;
    private javax.swing.JButton v4;
    private javax.swing.JButton v5;
    private javax.swing.JButton v6;
    private javax.swing.JButton v7;
    private javax.swing.JButton v8;
    private javax.swing.JButton v9;
    // End of variables declaration//GEN-END:variables
}
